inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'bin/*'
  NewCops: enable

require:
  - rubocop-rails
  - rubocop-performance

# ==============================================================================
# Cops

# Style cops

Style/Documentation:
  Enabled: false

# Metrics cops

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Severity: warning
